// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: control.proto

package mbta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckMode int32

const (
	AckMode_ACK_MODE_UNSPECIFIED AckMode = 0
	AckMode_ACK_MODE_ACCEPTED    AckMode = 1 // 已接受，未持久化
	AckMode_ACK_MODE_DURABLE     AckMode = 2 // 已持久化（durable_ack）
)

// Enum value maps for AckMode.
var (
	AckMode_name = map[int32]string{
		0: "ACK_MODE_UNSPECIFIED",
		1: "ACK_MODE_ACCEPTED",
		2: "ACK_MODE_DURABLE",
	}
	AckMode_value = map[string]int32{
		"ACK_MODE_UNSPECIFIED": 0,
		"ACK_MODE_ACCEPTED":    1,
		"ACK_MODE_DURABLE":     2,
	}
)

func (x AckMode) Enum() *AckMode {
	p := new(AckMode)
	*p = x
	return p
}

func (x AckMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckMode) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (AckMode) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x AckMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckMode.Descriptor instead.
func (AckMode) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type HelloMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	FrameVersion  uint32                 `protobuf:"varint,5,opt,name=frame_version,json=frameVersion,proto3" json:"frame_version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ResourceClass *string                `protobuf:"bytes,7,opt,name=resource_class,json=resourceClass,proto3,oneof" json:"resource_class,omitempty"` // embedded/constrained/standard/server（§9.5）
	MemLimitKb    *uint64                `protobuf:"varint,8,opt,name=mem_limit_kb,json=memLimitKb,proto3,oneof" json:"mem_limit_kb,omitempty"`       // 受限场景触发服务端降级
	ConnId        string                 `protobuf:"bytes,9,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	StartedAtUnix int64                  `protobuf:"varint,10,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	SessionTicket []byte                 `protobuf:"bytes,11,opt,name=session_ticket,json=sessionTicket,proto3,oneof" json:"session_ticket,omitempty"` // r2 0-RTT：resumption ticket（上次 AUTH_OK 颁发）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloMessage) Reset() {
	*x = HelloMessage{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloMessage) ProtoMessage() {}

func (x *HelloMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloMessage.ProtoReflect.Descriptor instead.
func (*HelloMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *HelloMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HelloMessage) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HelloMessage) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HelloMessage) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HelloMessage) GetFrameVersion() uint32 {
	if x != nil {
		return x.FrameVersion
	}
	return 0
}

func (x *HelloMessage) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HelloMessage) GetResourceClass() string {
	if x != nil && x.ResourceClass != nil {
		return *x.ResourceClass
	}
	return ""
}

func (x *HelloMessage) GetMemLimitKb() uint64 {
	if x != nil && x.MemLimitKb != nil {
		return *x.MemLimitKb
	}
	return 0
}

func (x *HelloMessage) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *HelloMessage) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *HelloMessage) GetSessionTicket() []byte {
	if x != nil {
		return x.SessionTicket
	}
	return nil
}

type HelloAckMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerId             string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SelectedCapabilities []string               `protobuf:"bytes,3,rep,name=selected_capabilities,json=selectedCapabilities,proto3" json:"selected_capabilities,omitempty"`
	Codec                Codec                  `protobuf:"varint,4,opt,name=codec,proto3,enum=mbta.v1.Codec" json:"codec,omitempty"`
	Compression          Compression            `protobuf:"varint,5,opt,name=compression,proto3,enum=mbta.v1.Compression" json:"compression,omitempty"`
	CipherSuite          CipherSuite            `protobuf:"varint,6,opt,name=cipher_suite,json=cipherSuite,proto3,enum=mbta.v1.CipherSuite" json:"cipher_suite,omitempty"`
	MaxFramePayloadBytes uint32                 `protobuf:"varint,7,opt,name=max_frame_payload_bytes,json=maxFramePayloadBytes,proto3" json:"max_frame_payload_bytes,omitempty"`
	MaxBatchBytes        uint32                 `protobuf:"varint,8,opt,name=max_batch_bytes,json=maxBatchBytes,proto3" json:"max_batch_bytes,omitempty"`
	MaxBatchEvents       uint32                 `protobuf:"varint,9,opt,name=max_batch_events,json=maxBatchEvents,proto3" json:"max_batch_events,omitempty"`
	MaxEventBytes        uint32                 `protobuf:"varint,10,opt,name=max_event_bytes,json=maxEventBytes,proto3" json:"max_event_bytes,omitempty"`
	InitialWindow        *WindowMessage         `protobuf:"bytes,11,opt,name=initial_window,json=initialWindow,proto3" json:"initial_window,omitempty"`
	HeartbeatIntervalSec uint32                 `protobuf:"varint,12,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"`
	ChallengeNonce       []byte                 `protobuf:"bytes,13,opt,name=challenge_nonce,json=challengeNonce,proto3" json:"challenge_nonce,omitempty"` // 一次性挑战，供 AUTH 应答
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HelloAckMessage) Reset() {
	*x = HelloAckMessage{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAckMessage) ProtoMessage() {}

func (x *HelloAckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAckMessage.ProtoReflect.Descriptor instead.
func (*HelloAckMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *HelloAckMessage) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *HelloAckMessage) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *HelloAckMessage) GetSelectedCapabilities() []string {
	if x != nil {
		return x.SelectedCapabilities
	}
	return nil
}

func (x *HelloAckMessage) GetCodec() Codec {
	if x != nil {
		return x.Codec
	}
	return Codec_CODEC_UNSPECIFIED
}

func (x *HelloAckMessage) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_COMPRESSION_UNSPECIFIED
}

func (x *HelloAckMessage) GetCipherSuite() CipherSuite {
	if x != nil {
		return x.CipherSuite
	}
	return CipherSuite_CIPHER_SUITE_UNSPECIFIED
}

func (x *HelloAckMessage) GetMaxFramePayloadBytes() uint32 {
	if x != nil {
		return x.MaxFramePayloadBytes
	}
	return 0
}

func (x *HelloAckMessage) GetMaxBatchBytes() uint32 {
	if x != nil {
		return x.MaxBatchBytes
	}
	return 0
}

func (x *HelloAckMessage) GetMaxBatchEvents() uint32 {
	if x != nil {
		return x.MaxBatchEvents
	}
	return 0
}

func (x *HelloAckMessage) GetMaxEventBytes() uint32 {
	if x != nil {
		return x.MaxEventBytes
	}
	return 0
}

func (x *HelloAckMessage) GetInitialWindow() *WindowMessage {
	if x != nil {
		return x.InitialWindow
	}
	return nil
}

func (x *HelloAckMessage) GetHeartbeatIntervalSec() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

func (x *HelloAckMessage) GetChallengeNonce() []byte {
	if x != nil {
		return x.ChallengeNonce
	}
	return nil
}

type AuthMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     []byte                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AuthNonce     []byte                 `protobuf:"bytes,4,opt,name=auth_nonce,json=authNonce,proto3" json:"auth_nonce,omitempty"`      // 基于 challenge_nonce 的应答
	Sm2CertPem    []byte                 `protobuf:"bytes,5,opt,name=sm2_cert_pem,json=sm2CertPem,proto3" json:"sm2_cert_pem,omitempty"` // sm2_cert_auth 协商时
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthMessage) Reset() {
	*x = AuthMessage{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMessage) ProtoMessage() {}

func (x *AuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMessage.ProtoReflect.Descriptor instead.
func (*AuthMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *AuthMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AuthMessage) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *AuthMessage) GetAuthNonce() []byte {
	if x != nil {
		return x.AuthNonce
	}
	return nil
}

func (x *AuthMessage) GetSm2CertPem() []byte {
	if x != nil {
		return x.Sm2CertPem
	}
	return nil
}

type AuthOKMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	HmacKey       []byte                 `protobuf:"bytes,3,opt,name=hmac_key,json=hmacKey,proto3" json:"hmac_key,omitempty"`
	AesKey        []byte                 `protobuf:"bytes,4,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"` // cipher_suite=intl 时
	Sm4Key        []byte                 `protobuf:"bytes,5,opt,name=sm4_key,json=sm4Key,proto3" json:"sm4_key,omitempty"` // cipher_suite=gm 时
	CipherSuite   CipherSuite            `protobuf:"varint,6,opt,name=cipher_suite,json=cipherSuite,proto3,enum=mbta.v1.CipherSuite" json:"cipher_suite,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,7,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	SessionTicket []byte                 `protobuf:"bytes,8,opt,name=session_ticket,json=sessionTicket,proto3,oneof" json:"session_ticket,omitempty"` // r2 0-RTT：新 session ticket（client 保存用于下次 resumption）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthOKMessage) Reset() {
	*x = AuthOKMessage{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOKMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOKMessage) ProtoMessage() {}

func (x *AuthOKMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOKMessage.ProtoReflect.Descriptor instead.
func (*AuthOKMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *AuthOKMessage) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *AuthOKMessage) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *AuthOKMessage) GetHmacKey() []byte {
	if x != nil {
		return x.HmacKey
	}
	return nil
}

func (x *AuthOKMessage) GetAesKey() []byte {
	if x != nil {
		return x.AesKey
	}
	return nil
}

func (x *AuthOKMessage) GetSm4Key() []byte {
	if x != nil {
		return x.Sm4Key
	}
	return nil
}

func (x *AuthOKMessage) GetCipherSuite() CipherSuite {
	if x != nil {
		return x.CipherSuite
	}
	return CipherSuite_CIPHER_SUITE_UNSPECIFIED
}

func (x *AuthOKMessage) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *AuthOKMessage) GetSessionTicket() []byte {
	if x != nil {
		return x.SessionTicket
	}
	return nil
}

type AuthFailMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Retryable      bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	ChallengeNonce []byte                 `protobuf:"bytes,4,opt,name=challenge_nonce,json=challengeNonce,proto3" json:"challenge_nonce,omitempty"` // retryable 时回传新挑战
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthFailMessage) Reset() {
	*x = AuthFailMessage{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthFailMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthFailMessage) ProtoMessage() {}

func (x *AuthFailMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthFailMessage.ProtoReflect.Descriptor instead.
func (*AuthFailMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *AuthFailMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AuthFailMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuthFailMessage) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *AuthFailMessage) GetChallengeNonce() []byte {
	if x != nil {
		return x.ChallengeNonce
	}
	return nil
}

type BatchMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ChunkId       []byte                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"` // ULID 16B
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	EventsCount   int32                  `protobuf:"varint,5,opt,name=events_count,json=eventsCount,proto3" json:"events_count,omitempty"` // 供 RawEventSink 快速路径
	Batch         []byte                 `protobuf:"bytes,6,opt,name=batch,proto3" json:"batch,omitempty"`                                 // SignalBatch 编码字节
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMessage) Reset() {
	*x = BatchMessage{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMessage) ProtoMessage() {}

func (x *BatchMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMessage.ProtoReflect.Descriptor instead.
func (*BatchMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *BatchMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *BatchMessage) GetChunkId() []byte {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *BatchMessage) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *BatchMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BatchMessage) GetEventsCount() int32 {
	if x != nil {
		return x.EventsCount
	}
	return 0
}

func (x *BatchMessage) GetBatch() []byte {
	if x != nil {
		return x.Batch
	}
	return nil
}

type DatagramMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ChunkId       []byte                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"` // 可选，仅采样/关联
	Batch         []byte                 `protobuf:"bytes,3,opt,name=batch,proto3" json:"batch,omitempty"`
	EventsCount   int32                  `protobuf:"varint,4,opt,name=events_count,json=eventsCount,proto3" json:"events_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatagramMessage) Reset() {
	*x = DatagramMessage{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatagramMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatagramMessage) ProtoMessage() {}

func (x *DatagramMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatagramMessage.ProtoReflect.Descriptor instead.
func (*DatagramMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *DatagramMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *DatagramMessage) GetChunkId() []byte {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *DatagramMessage) GetBatch() []byte {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *DatagramMessage) GetEventsCount() int32 {
	if x != nil {
		return x.EventsCount
	}
	return 0
}

type AckMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Seq              uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ChunkId          []byte                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Count            int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	AckMode          AckMode                `protobuf:"varint,4,opt,name=ack_mode,json=ackMode,proto3,enum=mbta.v1.AckMode" json:"ack_mode,omitempty"`
	ReceivedAtUnixMs int64                  `protobuf:"varint,5,opt,name=received_at_unix_ms,json=receivedAtUnixMs,proto3" json:"received_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AckMessage) Reset() {
	*x = AckMessage{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessage) ProtoMessage() {}

func (x *AckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessage.ProtoReflect.Descriptor instead.
func (*AckMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *AckMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AckMessage) GetChunkId() []byte {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *AckMessage) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AckMessage) GetAckMode() AckMode {
	if x != nil {
		return x.AckMode
	}
	return AckMode_ACK_MODE_UNSPECIFIED
}

func (x *AckMessage) GetReceivedAtUnixMs() int64 {
	if x != nil {
		return x.ReceivedAtUnixMs
	}
	return 0
}

type NackMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ChunkId       []byte                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Retryable     bool                   `protobuf:"varint,5,opt,name=retryable,proto3" json:"retryable,omitempty"`
	RetryAfterMs  int32                  `protobuf:"varint,6,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackMessage) Reset() {
	*x = NackMessage{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackMessage) ProtoMessage() {}

func (x *NackMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackMessage.ProtoReflect.Descriptor instead.
func (*NackMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *NackMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *NackMessage) GetChunkId() []byte {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *NackMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *NackMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *NackMessage) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *NackMessage) GetRetryAfterMs() int32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

type RejectedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Retryable     bool                   `protobuf:"varint,5,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectedEvent) Reset() {
	*x = RejectedEvent{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectedEvent) ProtoMessage() {}

func (x *RejectedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectedEvent.ProtoReflect.Descriptor instead.
func (*RejectedEvent) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *RejectedEvent) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RejectedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RejectedEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RejectedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RejectedEvent) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type PartialAckMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Seq            uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ChunkId        []byte                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	AckMode        AckMode                `protobuf:"varint,3,opt,name=ack_mode,json=ackMode,proto3,enum=mbta.v1.AckMode" json:"ack_mode,omitempty"`
	Accepted       []uint32               `protobuf:"varint,4,rep,packed,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected       []*RejectedEvent       `protobuf:"bytes,5,rep,name=rejected,proto3" json:"rejected,omitempty"`
	RejectedBitmap []byte                 `protobuf:"bytes,6,opt,name=rejected_bitmap,json=rejectedBitmap,proto3,oneof" json:"rejected_bitmap,omitempty"` // 大 batch 紧凑表达（§4.1）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PartialAckMessage) Reset() {
	*x = PartialAckMessage{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialAckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialAckMessage) ProtoMessage() {}

func (x *PartialAckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialAckMessage.ProtoReflect.Descriptor instead.
func (*PartialAckMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *PartialAckMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PartialAckMessage) GetChunkId() []byte {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *PartialAckMessage) GetAckMode() AckMode {
	if x != nil {
		return x.AckMode
	}
	return AckMode_ACK_MODE_UNSPECIFIED
}

func (x *PartialAckMessage) GetAccepted() []uint32 {
	if x != nil {
		return x.Accepted
	}
	return nil
}

func (x *PartialAckMessage) GetRejected() []*RejectedEvent {
	if x != nil {
		return x.Rejected
	}
	return nil
}

func (x *PartialAckMessage) GetRejectedBitmap() []byte {
	if x != nil {
		return x.RejectedBitmap
	}
	return nil
}

type WindowMessage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaxInflightBatches int32                  `protobuf:"varint,1,opt,name=max_inflight_batches,json=maxInflightBatches,proto3" json:"max_inflight_batches,omitempty"`
	MaxInflightEvents  int32                  `protobuf:"varint,2,opt,name=max_inflight_events,json=maxInflightEvents,proto3" json:"max_inflight_events,omitempty"`
	MaxInflightBytes   int64                  `protobuf:"varint,3,opt,name=max_inflight_bytes,json=maxInflightBytes,proto3" json:"max_inflight_bytes,omitempty"`
	Reason             string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WindowMessage) Reset() {
	*x = WindowMessage{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowMessage) ProtoMessage() {}

func (x *WindowMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowMessage.ProtoReflect.Descriptor instead.
func (*WindowMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *WindowMessage) GetMaxInflightBatches() int32 {
	if x != nil {
		return x.MaxInflightBatches
	}
	return 0
}

func (x *WindowMessage) GetMaxInflightEvents() int32 {
	if x != nil {
		return x.MaxInflightEvents
	}
	return 0
}

func (x *WindowMessage) GetMaxInflightBytes() int64 {
	if x != nil {
		return x.MaxInflightBytes
	}
	return 0
}

func (x *WindowMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ThrottleMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetryDelayMs  int32                  `protobuf:"varint,1,opt,name=retry_delay_ms,json=retryDelayMs,proto3" json:"retry_delay_ms,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThrottleMessage) Reset() {
	*x = ThrottleMessage{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThrottleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrottleMessage) ProtoMessage() {}

func (x *ThrottleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrottleMessage.ProtoReflect.Descriptor instead.
func (*ThrottleMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *ThrottleMessage) GetRetryDelayMs() int32 {
	if x != nil {
		return x.RetryDelayMs
	}
	return 0
}

func (x *ThrottleMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ThrottleMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeUnixMs    int64                  `protobuf:"varint,1,opt,name=time_unix_ms,json=timeUnixMs,proto3" json:"time_unix_ms,omitempty"`
	Nonce         string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingMessage) Reset() {
	*x = PingMessage{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMessage) ProtoMessage() {}

func (x *PingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMessage.ProtoReflect.Descriptor instead.
func (*PingMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *PingMessage) GetTimeUnixMs() int64 {
	if x != nil {
		return x.TimeUnixMs
	}
	return 0
}

func (x *PingMessage) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type PongMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeUnixMs    int64                  `protobuf:"varint,1,opt,name=time_unix_ms,json=timeUnixMs,proto3" json:"time_unix_ms,omitempty"`
	Nonce         string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // ok / degraded（可携带自省）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongMessage) Reset() {
	*x = PongMessage{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongMessage) ProtoMessage() {}

func (x *PongMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongMessage.ProtoReflect.Descriptor instead.
func (*PongMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

func (x *PongMessage) GetTimeUnixMs() int64 {
	if x != nil {
		return x.TimeUnixMs
	}
	return 0
}

func (x *PongMessage) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *PongMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CloseMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	CloseTimeoutMs *uint32                `protobuf:"varint,3,opt,name=close_timeout_ms,json=closeTimeoutMs,proto3,oneof" json:"close_timeout_ms,omitempty"` // 优雅关闭 drain 超时（§9.6）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CloseMessage) Reset() {
	*x = CloseMessage{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseMessage) ProtoMessage() {}

func (x *CloseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseMessage.ProtoReflect.Descriptor instead.
func (*CloseMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

func (x *CloseMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CloseMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CloseMessage) GetCloseTimeoutMs() uint32 {
	if x != nil && x.CloseTimeoutMs != nil {
		return *x.CloseTimeoutMs
	}
	return 0
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumCode       uint32                 `protobuf:"varint,1,opt,name=num_code,json=numCode,proto3" json:"num_code,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Fatal         bool                   `protobuf:"varint,4,opt,name=fatal,proto3" json:"fatal,omitempty"`
	Retryable     bool                   `protobuf:"varint,5,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{16}
}

func (x *ErrorMessage) GetNumCode() uint32 {
	if x != nil {
		return x.NumCode
	}
	return 0
}

func (x *ErrorMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorMessage) GetFatal() bool {
	if x != nil {
		return x.Fatal
	}
	return false
}

func (x *ErrorMessage) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\ambta.v1\x1a\x0eenvelope.proto\"\xcb\x03\n" +
	"\fHelloMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12#\n" +
	"\rframe_version\x18\x05 \x01(\rR\fframeVersion\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12*\n" +
	"\x0eresource_class\x18\a \x01(\tH\x00R\rresourceClass\x88\x01\x01\x12%\n" +
	"\fmem_limit_kb\x18\b \x01(\x04H\x01R\n" +
	"memLimitKb\x88\x01\x01\x12\x17\n" +
	"\aconn_id\x18\t \x01(\tR\x06connId\x12&\n" +
	"\x0fstarted_at_unix\x18\n" +
	" \x01(\x03R\rstartedAtUnix\x12*\n" +
	"\x0esession_ticket\x18\v \x01(\fH\x02R\rsessionTicket\x88\x01\x01B\x11\n" +
	"\x0f_resource_classB\x0f\n" +
	"\r_mem_limit_kbB\x11\n" +
	"\x0f_session_ticket\"\xe8\x04\n" +
	"\x0fHelloAckMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x123\n" +
	"\x15selected_capabilities\x18\x03 \x03(\tR\x14selectedCapabilities\x12$\n" +
	"\x05codec\x18\x04 \x01(\x0e2\x0e.mbta.v1.CodecR\x05codec\x126\n" +
	"\vcompression\x18\x05 \x01(\x0e2\x14.mbta.v1.CompressionR\vcompression\x127\n" +
	"\fcipher_suite\x18\x06 \x01(\x0e2\x14.mbta.v1.CipherSuiteR\vcipherSuite\x125\n" +
	"\x17max_frame_payload_bytes\x18\a \x01(\rR\x14maxFramePayloadBytes\x12&\n" +
	"\x0fmax_batch_bytes\x18\b \x01(\rR\rmaxBatchBytes\x12(\n" +
	"\x10max_batch_events\x18\t \x01(\rR\x0emaxBatchEvents\x12&\n" +
	"\x0fmax_event_bytes\x18\n" +
	" \x01(\rR\rmaxEventBytes\x12=\n" +
	"\x0einitial_window\x18\v \x01(\v2\x16.mbta.v1.WindowMessageR\rinitialWindow\x124\n" +
	"\x16heartbeat_interval_sec\x18\f \x01(\rR\x14heartbeatIntervalSec\x12'\n" +
	"\x0fchallenge_nonce\x18\r \x01(\fR\x0echallengeNonce\"\x9e\x01\n" +
	"\vAuthMessage\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\fR\tsessionId\x12\x1d\n" +
	"\n" +
	"auth_nonce\x18\x04 \x01(\fR\tauthNonce\x12 \n" +
	"\fsm2_cert_pem\x18\x05 \x01(\fR\n" +
	"sm2CertPem\"\xb2\x02\n" +
	"\rAuthOKMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x19\n" +
	"\bhmac_key\x18\x03 \x01(\fR\ahmacKey\x12\x17\n" +
	"\aaes_key\x18\x04 \x01(\fR\x06aesKey\x12\x17\n" +
	"\asm4_key\x18\x05 \x01(\fR\x06sm4Key\x127\n" +
	"\fcipher_suite\x18\x06 \x01(\x0e2\x14.mbta.v1.CipherSuiteR\vcipherSuite\x12&\n" +
	"\x0fexpires_at_unix\x18\a \x01(\x03R\rexpiresAtUnix\x12*\n" +
	"\x0esession_ticket\x18\b \x01(\fH\x00R\rsessionTicket\x88\x01\x01B\x11\n" +
	"\x0f_session_ticket\"\x84\x01\n" +
	"\x0fAuthFailMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12'\n" +
	"\x0fchallenge_nonce\x18\x04 \x01(\fR\x0echallengeNonce\"\x9e\x01\n" +
	"\fBatchMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\fR\achunkId\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12!\n" +
	"\fevents_count\x18\x05 \x01(\x05R\veventsCount\x12\x14\n" +
	"\x05batch\x18\x06 \x01(\fR\x05batch\"w\n" +
	"\x0fDatagramMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\fR\achunkId\x12\x14\n" +
	"\x05batch\x18\x03 \x01(\fR\x05batch\x12!\n" +
	"\fevents_count\x18\x04 \x01(\x05R\veventsCount\"\xab\x01\n" +
	"\n" +
	"AckMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\fR\achunkId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12+\n" +
	"\back_mode\x18\x04 \x01(\x0e2\x10.mbta.v1.AckModeR\aackMode\x12-\n" +
	"\x13received_at_unix_ms\x18\x05 \x01(\x03R\x10receivedAtUnixMs\"\xaa\x01\n" +
	"\vNackMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\fR\achunkId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1c\n" +
	"\tretryable\x18\x05 \x01(\bR\tretryable\x12$\n" +
	"\x0eretry_after_ms\x18\x06 \x01(\x05R\fretryAfterMs\"\x8a\x01\n" +
	"\rRejectedEvent\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1c\n" +
	"\tretryable\x18\x05 \x01(\bR\tretryable\"\xff\x01\n" +
	"\x11PartialAckMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\fR\achunkId\x12+\n" +
	"\back_mode\x18\x03 \x01(\x0e2\x10.mbta.v1.AckModeR\aackMode\x12\x1a\n" +
	"\baccepted\x18\x04 \x03(\rR\baccepted\x122\n" +
	"\brejected\x18\x05 \x03(\v2\x16.mbta.v1.RejectedEventR\brejected\x12,\n" +
	"\x0frejected_bitmap\x18\x06 \x01(\fH\x00R\x0erejectedBitmap\x88\x01\x01B\x12\n" +
	"\x10_rejected_bitmap\"\xb7\x01\n" +
	"\rWindowMessage\x120\n" +
	"\x14max_inflight_batches\x18\x01 \x01(\x05R\x12maxInflightBatches\x12.\n" +
	"\x13max_inflight_events\x18\x02 \x01(\x05R\x11maxInflightEvents\x12,\n" +
	"\x12max_inflight_bytes\x18\x03 \x01(\x03R\x10maxInflightBytes\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"c\n" +
	"\x0fThrottleMessage\x12$\n" +
	"\x0eretry_delay_ms\x18\x01 \x01(\x05R\fretryDelayMs\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"E\n" +
	"\vPingMessage\x12 \n" +
	"\ftime_unix_ms\x18\x01 \x01(\x03R\n" +
	"timeUnixMs\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\"]\n" +
	"\vPongMessage\x12 \n" +
	"\ftime_unix_ms\x18\x01 \x01(\x03R\n" +
	"timeUnixMs\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"~\n" +
	"\fCloseMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12-\n" +
	"\x10close_timeout_ms\x18\x03 \x01(\rH\x00R\x0ecloseTimeoutMs\x88\x01\x01B\x13\n" +
	"\x11_close_timeout_ms\"\x89\x01\n" +
	"\fErrorMessage\x12\x19\n" +
	"\bnum_code\x18\x01 \x01(\rR\anumCode\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x14\n" +
	"\x05fatal\x18\x04 \x01(\bR\x05fatal\x12\x1c\n" +
	"\tretryable\x18\x05 \x01(\bR\tretryable*P\n" +
	"\aAckMode\x12\x18\n" +
	"\x14ACK_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACK_MODE_ACCEPTED\x10\x01\x12\x14\n" +
	"\x10ACK_MODE_DURABLE\x10\x02B&Z$github.com/iuboy/mbta-go/corepb;mbtab\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_control_proto_goTypes = []any{
	(AckMode)(0),              // 0: mbta.v1.AckMode
	(*HelloMessage)(nil),      // 1: mbta.v1.HelloMessage
	(*HelloAckMessage)(nil),   // 2: mbta.v1.HelloAckMessage
	(*AuthMessage)(nil),       // 3: mbta.v1.AuthMessage
	(*AuthOKMessage)(nil),     // 4: mbta.v1.AuthOKMessage
	(*AuthFailMessage)(nil),   // 5: mbta.v1.AuthFailMessage
	(*BatchMessage)(nil),      // 6: mbta.v1.BatchMessage
	(*DatagramMessage)(nil),   // 7: mbta.v1.DatagramMessage
	(*AckMessage)(nil),        // 8: mbta.v1.AckMessage
	(*NackMessage)(nil),       // 9: mbta.v1.NackMessage
	(*RejectedEvent)(nil),     // 10: mbta.v1.RejectedEvent
	(*PartialAckMessage)(nil), // 11: mbta.v1.PartialAckMessage
	(*WindowMessage)(nil),     // 12: mbta.v1.WindowMessage
	(*ThrottleMessage)(nil),   // 13: mbta.v1.ThrottleMessage
	(*PingMessage)(nil),       // 14: mbta.v1.PingMessage
	(*PongMessage)(nil),       // 15: mbta.v1.PongMessage
	(*CloseMessage)(nil),      // 16: mbta.v1.CloseMessage
	(*ErrorMessage)(nil),      // 17: mbta.v1.ErrorMessage
	(Codec)(0),                // 18: mbta.v1.Codec
	(Compression)(0),          // 19: mbta.v1.Compression
	(CipherSuite)(0),          // 20: mbta.v1.CipherSuite
}
var file_control_proto_depIdxs = []int32{
	18, // 0: mbta.v1.HelloAckMessage.codec:type_name -> mbta.v1.Codec
	19, // 1: mbta.v1.HelloAckMessage.compression:type_name -> mbta.v1.Compression
	20, // 2: mbta.v1.HelloAckMessage.cipher_suite:type_name -> mbta.v1.CipherSuite
	12, // 3: mbta.v1.HelloAckMessage.initial_window:type_name -> mbta.v1.WindowMessage
	20, // 4: mbta.v1.AuthOKMessage.cipher_suite:type_name -> mbta.v1.CipherSuite
	0,  // 5: mbta.v1.AckMessage.ack_mode:type_name -> mbta.v1.AckMode
	0,  // 6: mbta.v1.PartialAckMessage.ack_mode:type_name -> mbta.v1.AckMode
	10, // 7: mbta.v1.PartialAckMessage.rejected:type_name -> mbta.v1.RejectedEvent
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_envelope_proto_init()
	file_control_proto_msgTypes[0].OneofWrappers = []any{}
	file_control_proto_msgTypes[3].OneofWrappers = []any{}
	file_control_proto_msgTypes[10].OneofWrappers = []any{}
	file_control_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
