// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: envelope.proto

package mbta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvelopeMsgType int32

const (
	EnvelopeMsgType_ENVELOPE_MSG_TYPE_UNSPECIFIED EnvelopeMsgType = 0
	EnvelopeMsgType_ENVELOPE_MSG_TYPE_BATCH       EnvelopeMsgType = 1
	EnvelopeMsgType_ENVELOPE_MSG_TYPE_DATAGRAM    EnvelopeMsgType = 2
)

// Enum value maps for EnvelopeMsgType.
var (
	EnvelopeMsgType_name = map[int32]string{
		0: "ENVELOPE_MSG_TYPE_UNSPECIFIED",
		1: "ENVELOPE_MSG_TYPE_BATCH",
		2: "ENVELOPE_MSG_TYPE_DATAGRAM",
	}
	EnvelopeMsgType_value = map[string]int32{
		"ENVELOPE_MSG_TYPE_UNSPECIFIED": 0,
		"ENVELOPE_MSG_TYPE_BATCH":       1,
		"ENVELOPE_MSG_TYPE_DATAGRAM":    2,
	}
)

func (x EnvelopeMsgType) Enum() *EnvelopeMsgType {
	p := new(EnvelopeMsgType)
	*p = x
	return p
}

func (x EnvelopeMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvelopeMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[0].Descriptor()
}

func (EnvelopeMsgType) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[0]
}

func (x EnvelopeMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvelopeMsgType.Descriptor instead.
func (EnvelopeMsgType) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

type Codec int32

const (
	Codec_CODEC_UNSPECIFIED Codec = 0
	Codec_CODEC_PROTO       Codec = 1 // baseline 默认
	Codec_CODEC_CBOR        Codec = 2 // constrained
	Codec_CODEC_JSON        Codec = 3 // 仅调试
)

// Enum value maps for Codec.
var (
	Codec_name = map[int32]string{
		0: "CODEC_UNSPECIFIED",
		1: "CODEC_PROTO",
		2: "CODEC_CBOR",
		3: "CODEC_JSON",
	}
	Codec_value = map[string]int32{
		"CODEC_UNSPECIFIED": 0,
		"CODEC_PROTO":       1,
		"CODEC_CBOR":        2,
		"CODEC_JSON":        3,
	}
)

func (x Codec) Enum() *Codec {
	p := new(Codec)
	*p = x
	return p
}

func (x Codec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Codec) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[1].Descriptor()
}

func (Codec) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[1]
}

func (x Codec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Codec.Descriptor instead.
func (Codec) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{1}
}

type Compression int32

const (
	Compression_COMPRESSION_UNSPECIFIED Compression = 0
	Compression_COMPRESSION_ZSTD        Compression = 1 // baseline 默认
	Compression_COMPRESSION_LZ4         Compression = 2 // constrained / 低延迟
	Compression_COMPRESSION_NONE        Compression = 3
	Compression_COMPRESSION_GZIP        Compression = 4 // legacy
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "COMPRESSION_UNSPECIFIED",
		1: "COMPRESSION_ZSTD",
		2: "COMPRESSION_LZ4",
		3: "COMPRESSION_NONE",
		4: "COMPRESSION_GZIP",
	}
	Compression_value = map[string]int32{
		"COMPRESSION_UNSPECIFIED": 0,
		"COMPRESSION_ZSTD":        1,
		"COMPRESSION_LZ4":         2,
		"COMPRESSION_NONE":        3,
		"COMPRESSION_GZIP":        4,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[2].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[2]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{2}
}

type CipherSuite int32

const (
	CipherSuite_CIPHER_SUITE_UNSPECIFIED CipherSuite = 0
	CipherSuite_CIPHER_SUITE_INTL        CipherSuite = 1 // SHA-256 + AES-256-GCM + ECDSA/Ed25519
	CipherSuite_CIPHER_SUITE_GM          CipherSuite = 2 // SM3 + SM4-GCM + SM2
)

// Enum value maps for CipherSuite.
var (
	CipherSuite_name = map[int32]string{
		0: "CIPHER_SUITE_UNSPECIFIED",
		1: "CIPHER_SUITE_INTL",
		2: "CIPHER_SUITE_GM",
	}
	CipherSuite_value = map[string]int32{
		"CIPHER_SUITE_UNSPECIFIED": 0,
		"CIPHER_SUITE_INTL":        1,
		"CIPHER_SUITE_GM":          2,
	}
)

func (x CipherSuite) Enum() *CipherSuite {
	p := new(CipherSuite)
	*p = x
	return p
}

func (x CipherSuite) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CipherSuite) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[3].Descriptor()
}

func (CipherSuite) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[3]
}

func (x CipherSuite) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CipherSuite.Descriptor instead.
func (CipherSuite) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{3}
}

type DeliveryMode int32

const (
	DeliveryMode_DELIVERY_MODE_UNSPECIFIED DeliveryMode = 0
	DeliveryMode_DELIVERY_MODE_RELIABLE    DeliveryMode = 1 // BATCH，at-least-once / effectively-once
	DeliveryMode_DELIVERY_MODE_LOSSY       DeliveryMode = 2 // DATAGRAM，at-most-once（§11.4）
)

// Enum value maps for DeliveryMode.
var (
	DeliveryMode_name = map[int32]string{
		0: "DELIVERY_MODE_UNSPECIFIED",
		1: "DELIVERY_MODE_RELIABLE",
		2: "DELIVERY_MODE_LOSSY",
	}
	DeliveryMode_value = map[string]int32{
		"DELIVERY_MODE_UNSPECIFIED": 0,
		"DELIVERY_MODE_RELIABLE":    1,
		"DELIVERY_MODE_LOSSY":       2,
	}
)

func (x DeliveryMode) Enum() *DeliveryMode {
	p := new(DeliveryMode)
	*p = x
	return p
}

func (x DeliveryMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryMode) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[4].Descriptor()
}

func (DeliveryMode) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[4]
}

func (x DeliveryMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryMode.Descriptor instead.
func (DeliveryMode) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{4}
}

// SecureEnvelope 是压缩、加密、认证的唯一承载点（core spec §5）。
// payload/mac/nonce 为原生 bytes（去 base64）。HMAC 签名输入为
// proto.MarshalOptions{Deterministic:true} 对 mac 清空后的 envelope（§5.3）。
// 本 message 内禁止 map 字段，以保证 HMAC 跨实现确定性。
type SecureEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnvelopeVersion uint32                 `protobuf:"varint,1,opt,name=envelope_version,json=envelopeVersion,proto3" json:"envelope_version,omitempty"`
	MessageType     EnvelopeMsgType        `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=mbta.v1.EnvelopeMsgType" json:"message_type,omitempty"`
	SessionId       []byte                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	KeyId           []byte                 `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Seq             uint64                 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`                       // 仅 reliable BATCH
	ChunkId         []byte                 `protobuf:"bytes,6,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"` // ULID 16B（仅 reliable BATCH；datagram 可选）
	CreatedAtUnixMs int64                  `protobuf:"varint,7,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	Codec           Codec                  `protobuf:"varint,8,opt,name=codec,proto3,enum=mbta.v1.Codec" json:"codec,omitempty"`
	Compression     Compression            `protobuf:"varint,9,opt,name=compression,proto3,enum=mbta.v1.Compression" json:"compression,omitempty"`
	CipherSuite     CipherSuite            `protobuf:"varint,10,opt,name=cipher_suite,json=cipherSuite,proto3,enum=mbta.v1.CipherSuite" json:"cipher_suite,omitempty"` // 替代散装 hmac_algo/encryption（§8.2）
	DeliveryMode    DeliveryMode           `protobuf:"varint,11,opt,name=delivery_mode,json=deliveryMode,proto3,enum=mbta.v1.DeliveryMode" json:"delivery_mode,omitempty"`
	Nonce           []byte                 `protobuf:"bytes,12,opt,name=nonce,proto3" json:"nonce,omitempty"`     // 显式 nonce，同密钥下禁止复用
	Payload         []byte                 `protobuf:"bytes,13,opt,name=payload,proto3" json:"payload,omitempty"` // 加密/压缩后载荷
	Mac             []byte                 `protobuf:"bytes,14,opt,name=mac,proto3" json:"mac,omitempty"`         // HMAC 输出
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SecureEnvelope) Reset() {
	*x = SecureEnvelope{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecureEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureEnvelope) ProtoMessage() {}

func (x *SecureEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureEnvelope.ProtoReflect.Descriptor instead.
func (*SecureEnvelope) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *SecureEnvelope) GetEnvelopeVersion() uint32 {
	if x != nil {
		return x.EnvelopeVersion
	}
	return 0
}

func (x *SecureEnvelope) GetMessageType() EnvelopeMsgType {
	if x != nil {
		return x.MessageType
	}
	return EnvelopeMsgType_ENVELOPE_MSG_TYPE_UNSPECIFIED
}

func (x *SecureEnvelope) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *SecureEnvelope) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

func (x *SecureEnvelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SecureEnvelope) GetChunkId() []byte {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *SecureEnvelope) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *SecureEnvelope) GetCodec() Codec {
	if x != nil {
		return x.Codec
	}
	return Codec_CODEC_UNSPECIFIED
}

func (x *SecureEnvelope) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_COMPRESSION_UNSPECIFIED
}

func (x *SecureEnvelope) GetCipherSuite() CipherSuite {
	if x != nil {
		return x.CipherSuite
	}
	return CipherSuite_CIPHER_SUITE_UNSPECIFIED
}

func (x *SecureEnvelope) GetDeliveryMode() DeliveryMode {
	if x != nil {
		return x.DeliveryMode
	}
	return DeliveryMode_DELIVERY_MODE_UNSPECIFIED
}

func (x *SecureEnvelope) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *SecureEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SecureEnvelope) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\ambta.v1\"\x9d\x04\n" +
	"\x0eSecureEnvelope\x12)\n" +
	"\x10envelope_version\x18\x01 \x01(\rR\x0fenvelopeVersion\x12;\n" +
	"\fmessage_type\x18\x02 \x01(\x0e2\x18.mbta.v1.EnvelopeMsgTypeR\vmessageType\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\fR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\fR\x05keyId\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x04R\x03seq\x12\x19\n" +
	"\bchunk_id\x18\x06 \x01(\fR\achunkId\x12+\n" +
	"\x12created_at_unix_ms\x18\a \x01(\x03R\x0fcreatedAtUnixMs\x12$\n" +
	"\x05codec\x18\b \x01(\x0e2\x0e.mbta.v1.CodecR\x05codec\x126\n" +
	"\vcompression\x18\t \x01(\x0e2\x14.mbta.v1.CompressionR\vcompression\x127\n" +
	"\fcipher_suite\x18\n" +
	" \x01(\x0e2\x14.mbta.v1.CipherSuiteR\vcipherSuite\x12:\n" +
	"\rdelivery_mode\x18\v \x01(\x0e2\x15.mbta.v1.DeliveryModeR\fdeliveryMode\x12\x14\n" +
	"\x05nonce\x18\f \x01(\fR\x05nonce\x12\x18\n" +
	"\apayload\x18\r \x01(\fR\apayload\x12\x10\n" +
	"\x03mac\x18\x0e \x01(\fR\x03mac*q\n" +
	"\x0fEnvelopeMsgType\x12!\n" +
	"\x1dENVELOPE_MSG_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ENVELOPE_MSG_TYPE_BATCH\x10\x01\x12\x1e\n" +
	"\x1aENVELOPE_MSG_TYPE_DATAGRAM\x10\x02*O\n" +
	"\x05Codec\x12\x15\n" +
	"\x11CODEC_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCODEC_PROTO\x10\x01\x12\x0e\n" +
	"\n" +
	"CODEC_CBOR\x10\x02\x12\x0e\n" +
	"\n" +
	"CODEC_JSON\x10\x03*\x81\x01\n" +
	"\vCompression\x12\x1b\n" +
	"\x17COMPRESSION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COMPRESSION_ZSTD\x10\x01\x12\x13\n" +
	"\x0fCOMPRESSION_LZ4\x10\x02\x12\x14\n" +
	"\x10COMPRESSION_NONE\x10\x03\x12\x14\n" +
	"\x10COMPRESSION_GZIP\x10\x04*W\n" +
	"\vCipherSuite\x12\x1c\n" +
	"\x18CIPHER_SUITE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CIPHER_SUITE_INTL\x10\x01\x12\x13\n" +
	"\x0fCIPHER_SUITE_GM\x10\x02*b\n" +
	"\fDeliveryMode\x12\x1d\n" +
	"\x19DELIVERY_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DELIVERY_MODE_RELIABLE\x10\x01\x12\x17\n" +
	"\x13DELIVERY_MODE_LOSSY\x10\x02B&Z$github.com/iuboy/mbta-go/corepb;mbtab\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envelope_proto_goTypes = []any{
	(EnvelopeMsgType)(0),   // 0: mbta.v1.EnvelopeMsgType
	(Codec)(0),             // 1: mbta.v1.Codec
	(Compression)(0),       // 2: mbta.v1.Compression
	(CipherSuite)(0),       // 3: mbta.v1.CipherSuite
	(DeliveryMode)(0),      // 4: mbta.v1.DeliveryMode
	(*SecureEnvelope)(nil), // 5: mbta.v1.SecureEnvelope
}
var file_envelope_proto_depIdxs = []int32{
	0, // 0: mbta.v1.SecureEnvelope.message_type:type_name -> mbta.v1.EnvelopeMsgType
	1, // 1: mbta.v1.SecureEnvelope.codec:type_name -> mbta.v1.Codec
	2, // 2: mbta.v1.SecureEnvelope.compression:type_name -> mbta.v1.Compression
	3, // 3: mbta.v1.SecureEnvelope.cipher_suite:type_name -> mbta.v1.CipherSuite
	4, // 4: mbta.v1.SecureEnvelope.delivery_mode:type_name -> mbta.v1.DeliveryMode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		EnumInfos:         file_envelope_proto_enumTypes,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
