// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: signal.proto

package mbta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignalBatch 对齐 OpenTelemetry 分层：Resource + InstrumentationScope + signals（§6）。
// Server 侧 MUST 能无损映射到 OTLP Logs/Metrics/Traces/Profiles（附录 C）。
type SignalBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaUrl     string                 `protobuf:"bytes,1,opt,name=schema_url,json=schemaUrl,proto3" json:"schema_url,omitempty"`
	Resource      *Resource              `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Scope         *InstrumentationScope  `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Signals       []*SignalRecord        `protobuf:"bytes,4,rep,name=signals,proto3" json:"signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalBatch) Reset() {
	*x = SignalBatch{}
	mi := &file_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalBatch) ProtoMessage() {}

func (x *SignalBatch) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalBatch.ProtoReflect.Descriptor instead.
func (*SignalBatch) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{0}
}

func (x *SignalBatch) GetSchemaUrl() string {
	if x != nil {
		return x.SchemaUrl
	}
	return ""
}

func (x *SignalBatch) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *SignalBatch) GetScope() *InstrumentationScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *SignalBatch) GetSignals() []*SignalRecord {
	if x != nil {
		return x.Signals
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    map[string]*AnyValue   `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetAttributes() map[string]*AnyValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type InstrumentationScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	CollectorId   string                 `protobuf:"bytes,3,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrumentationScope) Reset() {
	*x = InstrumentationScope{}
	mi := &file_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentationScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentationScope) ProtoMessage() {}

func (x *InstrumentationScope) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentationScope.ProtoReflect.Descriptor instead.
func (*InstrumentationScope) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{2}
}

func (x *InstrumentationScope) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstrumentationScope) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstrumentationScope) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

// AnyValue 表达动态类型字段（body、attributes 值）。
type AnyValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*AnyValue_StringValue
	//	*AnyValue_IntValue
	//	*AnyValue_DoubleValue
	//	*AnyValue_BytesValue
	//	*AnyValue_BoolValue
	Value         isAnyValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyValue) Reset() {
	*x = AnyValue{}
	mi := &file_signal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyValue) ProtoMessage() {}

func (x *AnyValue) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyValue.ProtoReflect.Descriptor instead.
func (*AnyValue) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{3}
}

func (x *AnyValue) GetValue() isAnyValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AnyValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AnyValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *AnyValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *AnyValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *AnyValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isAnyValue_Value interface {
	isAnyValue_Value()
}

type AnyValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AnyValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AnyValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type AnyValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,4,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type AnyValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*AnyValue_StringValue) isAnyValue_Value() {}

func (*AnyValue_IntValue) isAnyValue_Value() {}

func (*AnyValue_DoubleValue) isAnyValue_Value() {}

func (*AnyValue_BytesValue) isAnyValue_Value() {}

func (*AnyValue_BoolValue) isAnyValue_Value() {}

// histogram signal 的 exponential bucket 表达（§6.2，OTel Exponential Histogram）。
type ExponentialHistogram struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Scale           int32                  `protobuf:"varint,1,opt,name=scale,proto3" json:"scale,omitempty"`
	Offset          int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	PositiveBuckets []uint64               `protobuf:"varint,3,rep,packed,name=positive_buckets,json=positiveBuckets,proto3" json:"positive_buckets,omitempty"`
	NegativeBuckets []uint64               `protobuf:"varint,4,rep,packed,name=negative_buckets,json=negativeBuckets,proto3" json:"negative_buckets,omitempty"`
	Sum             float64                `protobuf:"fixed64,5,opt,name=sum,proto3" json:"sum,omitempty"`
	Count           uint64                 `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Min             *float64               `protobuf:"fixed64,7,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max             *float64               `protobuf:"fixed64,8,opt,name=max,proto3,oneof" json:"max,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExponentialHistogram) Reset() {
	*x = ExponentialHistogram{}
	mi := &file_signal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExponentialHistogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExponentialHistogram) ProtoMessage() {}

func (x *ExponentialHistogram) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExponentialHistogram.ProtoReflect.Descriptor instead.
func (*ExponentialHistogram) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{4}
}

func (x *ExponentialHistogram) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *ExponentialHistogram) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ExponentialHistogram) GetPositiveBuckets() []uint64 {
	if x != nil {
		return x.PositiveBuckets
	}
	return nil
}

func (x *ExponentialHistogram) GetNegativeBuckets() []uint64 {
	if x != nil {
		return x.NegativeBuckets
	}
	return nil
}

func (x *ExponentialHistogram) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *ExponentialHistogram) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ExponentialHistogram) GetMin() float64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *ExponentialHistogram) GetMax() float64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

// profile signal 载荷 + 与其他信号的双向关联（§6.2，OTLP v1.3.0+）。
type ProfilePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileType   string                 `protobuf:"bytes,1,opt,name=profile_type,json=profileType,proto3" json:"profile_type,omitempty"` // cpu / heap / mutex / goroutine ...
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ProfileId     string                 `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	TraceIdRef    string                 `protobuf:"bytes,4,opt,name=trace_id_ref,json=traceIdRef,proto3" json:"trace_id_ref,omitempty"`
	SpanIdRef     string                 `protobuf:"bytes,5,opt,name=span_id_ref,json=spanIdRef,proto3" json:"span_id_ref,omitempty"`
	LogRecordRef  string                 `protobuf:"bytes,6,opt,name=log_record_ref,json=logRecordRef,proto3" json:"log_record_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilePayload) Reset() {
	*x = ProfilePayload{}
	mi := &file_signal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilePayload) ProtoMessage() {}

func (x *ProfilePayload) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilePayload.ProtoReflect.Descriptor instead.
func (*ProfilePayload) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{5}
}

func (x *ProfilePayload) GetProfileType() string {
	if x != nil {
		return x.ProfileType
	}
	return ""
}

func (x *ProfilePayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProfilePayload) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ProfilePayload) GetTraceIdRef() string {
	if x != nil {
		return x.TraceIdRef
	}
	return ""
}

func (x *ProfilePayload) GetSpanIdRef() string {
	if x != nil {
		return x.SpanIdRef
	}
	return ""
}

func (x *ProfilePayload) GetLogRecordRef() string {
	if x != nil {
		return x.LogRecordRef
	}
	return ""
}

// 统一信号外壳。signal_type 必填；log MUST 用 "log"。
type SignalRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SignalType         string                 `protobuf:"bytes,1,opt,name=signal_type,json=signalType,proto3" json:"signal_type,omitempty"`
	EventId            string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TimeUnixMs         int64                  `protobuf:"varint,3,opt,name=time_unix_ms,json=timeUnixMs,proto3" json:"time_unix_ms,omitempty"`
	ObservedTimeUnixMs int64                  `protobuf:"varint,4,opt,name=observed_time_unix_ms,json=observedTimeUnixMs,proto3" json:"observed_time_unix_ms,omitempty"`
	TraceId            string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId             string                 `protobuf:"bytes,6,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId       string                 `protobuf:"bytes,7,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	Attributes         map[string]*AnyValue   `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body               *AnyValue              `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty"`
	SeverityNumber     int32                  `protobuf:"varint,10,opt,name=severity_number,json=severityNumber,proto3" json:"severity_number,omitempty"`
	SeverityText       string                 `protobuf:"bytes,11,opt,name=severity_text,json=severityText,proto3" json:"severity_text,omitempty"`
	MetricName         string                 `protobuf:"bytes,12,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	MetricFields       map[string]float64     `protobuf:"bytes,13,rep,name=metric_fields,json=metricFields,proto3" json:"metric_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Unit               string                 `protobuf:"bytes,14,opt,name=unit,proto3" json:"unit,omitempty"`
	Temporality        string                 `protobuf:"bytes,15,opt,name=temporality,proto3" json:"temporality,omitempty"`
	IsMonotonic        bool                   `protobuf:"varint,16,opt,name=is_monotonic,json=isMonotonic,proto3" json:"is_monotonic,omitempty"`
	Name               string                 `protobuf:"bytes,17,opt,name=name,proto3" json:"name,omitempty"`
	Kind               string                 `protobuf:"bytes,18,opt,name=kind,proto3" json:"kind,omitempty"`
	StartTimeUnixMs    int64                  `protobuf:"varint,19,opt,name=start_time_unix_ms,json=startTimeUnixMs,proto3" json:"start_time_unix_ms,omitempty"`
	EndTimeUnixMs      int64                  `protobuf:"varint,20,opt,name=end_time_unix_ms,json=endTimeUnixMs,proto3" json:"end_time_unix_ms,omitempty"`
	StatusCode         string                 `protobuf:"bytes,21,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMessage      string                 `protobuf:"bytes,22,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	ExpHistogram       *ExponentialHistogram  `protobuf:"bytes,23,opt,name=exp_histogram,json=expHistogram,proto3" json:"exp_histogram,omitempty"` // signal_type=histogram 且 aggregation=exponential
	Profile            *ProfilePayload        `protobuf:"bytes,24,opt,name=profile,proto3" json:"profile,omitempty"`                               // signal_type=profile
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignalRecord) Reset() {
	*x = SignalRecord{}
	mi := &file_signal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRecord) ProtoMessage() {}

func (x *SignalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRecord.ProtoReflect.Descriptor instead.
func (*SignalRecord) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{6}
}

func (x *SignalRecord) GetSignalType() string {
	if x != nil {
		return x.SignalType
	}
	return ""
}

func (x *SignalRecord) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SignalRecord) GetTimeUnixMs() int64 {
	if x != nil {
		return x.TimeUnixMs
	}
	return 0
}

func (x *SignalRecord) GetObservedTimeUnixMs() int64 {
	if x != nil {
		return x.ObservedTimeUnixMs
	}
	return 0
}

func (x *SignalRecord) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SignalRecord) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *SignalRecord) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *SignalRecord) GetAttributes() map[string]*AnyValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *SignalRecord) GetBody() *AnyValue {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SignalRecord) GetSeverityNumber() int32 {
	if x != nil {
		return x.SeverityNumber
	}
	return 0
}

func (x *SignalRecord) GetSeverityText() string {
	if x != nil {
		return x.SeverityText
	}
	return ""
}

func (x *SignalRecord) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *SignalRecord) GetMetricFields() map[string]float64 {
	if x != nil {
		return x.MetricFields
	}
	return nil
}

func (x *SignalRecord) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *SignalRecord) GetTemporality() string {
	if x != nil {
		return x.Temporality
	}
	return ""
}

func (x *SignalRecord) GetIsMonotonic() bool {
	if x != nil {
		return x.IsMonotonic
	}
	return false
}

func (x *SignalRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignalRecord) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SignalRecord) GetStartTimeUnixMs() int64 {
	if x != nil {
		return x.StartTimeUnixMs
	}
	return 0
}

func (x *SignalRecord) GetEndTimeUnixMs() int64 {
	if x != nil {
		return x.EndTimeUnixMs
	}
	return 0
}

func (x *SignalRecord) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *SignalRecord) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *SignalRecord) GetExpHistogram() *ExponentialHistogram {
	if x != nil {
		return x.ExpHistogram
	}
	return nil
}

func (x *SignalRecord) GetProfile() *ProfilePayload {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_signal_proto protoreflect.FileDescriptor

const file_signal_proto_rawDesc = "" +
	"\n" +
	"\fsignal.proto\x12\ambta.v1\"\xc1\x01\n" +
	"\vSignalBatch\x12\x1d\n" +
	"\n" +
	"schema_url\x18\x01 \x01(\tR\tschemaUrl\x12-\n" +
	"\bresource\x18\x02 \x01(\v2\x11.mbta.v1.ResourceR\bresource\x123\n" +
	"\x05scope\x18\x03 \x01(\v2\x1d.mbta.v1.InstrumentationScopeR\x05scope\x12/\n" +
	"\asignals\x18\x04 \x03(\v2\x15.mbta.v1.SignalRecordR\asignals\"\x9f\x01\n" +
	"\bResource\x12A\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2!.mbta.v1.Resource.AttributesEntryR\n" +
	"attributes\x1aP\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.mbta.v1.AnyValueR\x05value:\x028\x01\"g\n" +
	"\x14InstrumentationScope\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fcollector_id\x18\x03 \x01(\tR\vcollectorId\"\xc0\x01\n" +
	"\bAnyValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12!\n" +
	"\vbytes_value\x18\x04 \x01(\fH\x00R\n" +
	"bytesValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x05 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value\"\x80\x02\n" +
	"\x14ExponentialHistogram\x12\x14\n" +
	"\x05scale\x18\x01 \x01(\x05R\x05scale\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12)\n" +
	"\x10positive_buckets\x18\x03 \x03(\x04R\x0fpositiveBuckets\x12)\n" +
	"\x10negative_buckets\x18\x04 \x03(\x04R\x0fnegativeBuckets\x12\x10\n" +
	"\x03sum\x18\x05 \x01(\x01R\x03sum\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x04R\x05count\x12\x15\n" +
	"\x03min\x18\a \x01(\x01H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\b \x01(\x01H\x01R\x03max\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_max\"\xd4\x01\n" +
	"\x0eProfilePayload\x12!\n" +
	"\fprofile_type\x18\x01 \x01(\tR\vprofileType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tR\tprofileId\x12 \n" +
	"\ftrace_id_ref\x18\x04 \x01(\tR\n" +
	"traceIdRef\x12\x1e\n" +
	"\vspan_id_ref\x18\x05 \x01(\tR\tspanIdRef\x12$\n" +
	"\x0elog_record_ref\x18\x06 \x01(\tR\flogRecordRef\"\xcd\b\n" +
	"\fSignalRecord\x12\x1f\n" +
	"\vsignal_type\x18\x01 \x01(\tR\n" +
	"signalType\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12 \n" +
	"\ftime_unix_ms\x18\x03 \x01(\x03R\n" +
	"timeUnixMs\x121\n" +
	"\x15observed_time_unix_ms\x18\x04 \x01(\x03R\x12observedTimeUnixMs\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x06 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\a \x01(\tR\fparentSpanId\x12E\n" +
	"\n" +
	"attributes\x18\b \x03(\v2%.mbta.v1.SignalRecord.AttributesEntryR\n" +
	"attributes\x12%\n" +
	"\x04body\x18\t \x01(\v2\x11.mbta.v1.AnyValueR\x04body\x12'\n" +
	"\x0fseverity_number\x18\n" +
	" \x01(\x05R\x0eseverityNumber\x12#\n" +
	"\rseverity_text\x18\v \x01(\tR\fseverityText\x12\x1f\n" +
	"\vmetric_name\x18\f \x01(\tR\n" +
	"metricName\x12L\n" +
	"\rmetric_fields\x18\r \x03(\v2'.mbta.v1.SignalRecord.MetricFieldsEntryR\fmetricFields\x12\x12\n" +
	"\x04unit\x18\x0e \x01(\tR\x04unit\x12 \n" +
	"\vtemporality\x18\x0f \x01(\tR\vtemporality\x12!\n" +
	"\fis_monotonic\x18\x10 \x01(\bR\visMonotonic\x12\x12\n" +
	"\x04name\x18\x11 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x12 \x01(\tR\x04kind\x12+\n" +
	"\x12start_time_unix_ms\x18\x13 \x01(\x03R\x0fstartTimeUnixMs\x12'\n" +
	"\x10end_time_unix_ms\x18\x14 \x01(\x03R\rendTimeUnixMs\x12\x1f\n" +
	"\vstatus_code\x18\x15 \x01(\tR\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\x16 \x01(\tR\rstatusMessage\x12B\n" +
	"\rexp_histogram\x18\x17 \x01(\v2\x1d.mbta.v1.ExponentialHistogramR\fexpHistogram\x121\n" +
	"\aprofile\x18\x18 \x01(\v2\x17.mbta.v1.ProfilePayloadR\aprofile\x1aP\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.mbta.v1.AnyValueR\x05value:\x028\x01\x1a?\n" +
	"\x11MetricFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01B&Z$github.com/iuboy/mbta-go/corepb;mbtab\x06proto3"

var (
	file_signal_proto_rawDescOnce sync.Once
	file_signal_proto_rawDescData []byte
)

func file_signal_proto_rawDescGZIP() []byte {
	file_signal_proto_rawDescOnce.Do(func() {
		file_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signal_proto_rawDesc), len(file_signal_proto_rawDesc)))
	})
	return file_signal_proto_rawDescData
}

var file_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_signal_proto_goTypes = []any{
	(*SignalBatch)(nil),          // 0: mbta.v1.SignalBatch
	(*Resource)(nil),             // 1: mbta.v1.Resource
	(*InstrumentationScope)(nil), // 2: mbta.v1.InstrumentationScope
	(*AnyValue)(nil),             // 3: mbta.v1.AnyValue
	(*ExponentialHistogram)(nil), // 4: mbta.v1.ExponentialHistogram
	(*ProfilePayload)(nil),       // 5: mbta.v1.ProfilePayload
	(*SignalRecord)(nil),         // 6: mbta.v1.SignalRecord
	nil,                          // 7: mbta.v1.Resource.AttributesEntry
	nil,                          // 8: mbta.v1.SignalRecord.AttributesEntry
	nil,                          // 9: mbta.v1.SignalRecord.MetricFieldsEntry
}
var file_signal_proto_depIdxs = []int32{
	1,  // 0: mbta.v1.SignalBatch.resource:type_name -> mbta.v1.Resource
	2,  // 1: mbta.v1.SignalBatch.scope:type_name -> mbta.v1.InstrumentationScope
	6,  // 2: mbta.v1.SignalBatch.signals:type_name -> mbta.v1.SignalRecord
	7,  // 3: mbta.v1.Resource.attributes:type_name -> mbta.v1.Resource.AttributesEntry
	8,  // 4: mbta.v1.SignalRecord.attributes:type_name -> mbta.v1.SignalRecord.AttributesEntry
	3,  // 5: mbta.v1.SignalRecord.body:type_name -> mbta.v1.AnyValue
	9,  // 6: mbta.v1.SignalRecord.metric_fields:type_name -> mbta.v1.SignalRecord.MetricFieldsEntry
	4,  // 7: mbta.v1.SignalRecord.exp_histogram:type_name -> mbta.v1.ExponentialHistogram
	5,  // 8: mbta.v1.SignalRecord.profile:type_name -> mbta.v1.ProfilePayload
	3,  // 9: mbta.v1.Resource.AttributesEntry.value:type_name -> mbta.v1.AnyValue
	3,  // 10: mbta.v1.SignalRecord.AttributesEntry.value:type_name -> mbta.v1.AnyValue
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_signal_proto_init() }
func file_signal_proto_init() {
	if File_signal_proto != nil {
		return
	}
	file_signal_proto_msgTypes[3].OneofWrappers = []any{
		(*AnyValue_StringValue)(nil),
		(*AnyValue_IntValue)(nil),
		(*AnyValue_DoubleValue)(nil),
		(*AnyValue_BytesValue)(nil),
		(*AnyValue_BoolValue)(nil),
	}
	file_signal_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signal_proto_rawDesc), len(file_signal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_signal_proto_goTypes,
		DependencyIndexes: file_signal_proto_depIdxs,
		MessageInfos:      file_signal_proto_msgTypes,
	}.Build()
	File_signal_proto = out.File
	file_signal_proto_goTypes = nil
	file_signal_proto_depIdxs = nil
}
